
### Application configuration #####

spring:
  application:
    name: 'spring-mvc-demo'

  # This can be used to want to add ANSI colors to console log messages
  output.ansi.enabled: ALWAYS

  mvc:
    favicon.enabled: false
    log-resolved-exception: true

server.port: 8080

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: info,health,mappings,beans
  health:
    db.enabled: true

# The "logging" block configures the overall logging behavior
logging:
  # A custom config file can be used for maximum flexibility
  config: classpath:logback-dev.xml

