
### Application configuration #####

spring:
  application:
    name: 'spring-mvc-demo'

  # This can be used instead of custom logback configuration file if you just want to add
  # ANSI colors to the default console logging configuration
  # output.ansi.enabled: ALWAYS

server.port: 8080

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: info
  health:
    db.enabled: true

# The "logging" block configures the overall logging behavior
logging:
  # Use a custom config file for maximum flexibility
  config: classpath:logback-dev.xml
